# Generated by Django 4.1 on 2022-09-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoparser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
